### ISSUE TITLE
Password reminder doesn't support TLS website

### ISSUE THREAD

**Issue by adulau** [CASES-LU/zm-core#2]
The email notification system is building an URL/link from a http link only:

https://github.com/CASES-LU/zm-core/blob/dd1fe3bac4a9a1ad861f85462742bd873c22fe0e/src/MonarcCore/Service/PasswordService.php#L48

I see two main issues there:

 - Password reset process is using plain-text (any encryption foreseen?)
 - and the http scheme is hard-coded (some meaning running a MONARC server in TLS is not possible with adequate password notification)

I would recommend to rewrite and clean the process for generating urls and have a configuration
where the URL path is defined. I think this is quite important if you have people with proper HTTP configuration including WAF or reverse proxies.

**Comment by xplodwild** [comment]
I have fixed this in https://github.com/CASES-LU/zm-core/commit/8ad14bc7f1551617a15519fd217a4725db6d90da

The HTTP(S) proto is determined from the list of common HTTP header protos at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto, and the hostname is also determined from X-Forwarded-Host (with a fallback to `HTTP_HOST`).

This should handle most cases of reverse proxies (either for external SSL termination, and/or for cases where the application server is called from a different host than the public domain to the proxy).

We likely won't be able to handle non-root installs (ie. having the app in `/monarc/` for example) as most of the code has been designed to be at the root of the target domain. This is a possible evolution in the future I guess, but not a priority.

**Comment by adulau** [comment]
Thank you for the fix.
